name: SAFMN_FFT_STEM_p256b6_PairedRealMSELoss_8dbg
model_type: SRModel
scale: 1
num_gpu: 1
manual_seed: 12345

# ----------------- options for synthesizing training data in RealESRNetModel ----------------- #
gt_usm: False  # USM the ground-truth


#contrast_range: [0.4, 0.6]
#poisson_scale_range: [4, 8]
#gaussian_sigma_range: [1, 5]
##neighborhood_size: 15
##threshold_factor_range: [0.4, 0.6]
#compensation_range: [0.3, 0.6]
#resize_prob: [0., 0., 1]  # up, down, keep
#resize_range: [0.3, 1.5]
##sigma_1_range: [!!float 5e-2, !!float 5e-1]
##sigma_2_range: [!!float 1e-2, !!float 1e-1]
#randomshuffle: False

gt_size: 256
#queue_size: 128

datasets:
  train:
    name: ReSe2
    type: PairedImageDataset
    dataroot_gt: F:/Datasets/STEM ReSe2/ReSe2/paired/offset/debug/GT
    dataroot_lq: F:/Datasets/STEM ReSe2/ReSe2/paired/offset/debug/LQ
    color: gray
    meta_info: ~
    filename_tmpl: '{}'
    io_backend:
      type: disk
    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 1
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 100
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: ReSe2
    type: PairedImageDataset
    dataroot_gt: F:/Datasets/STEM ReSe2/ReSe2/paired/offset/GT_crops 256 256 png
    dataroot_lq: F:/Datasets/STEM ReSe2/ReSe2/paired/offset/LQ_crops 256 256 png
    color: gray
    io_backend:
      type: disk


network_g:
  type: SAFMN_FFT
  in_chans: 1
  dim: 36
  n_blocks: 12
  ffn_scale: 2.0
  upscaling_factor: 1

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-6
    weight_decay: 0.
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [100000]
    restart_weights: [1]
    eta_min: !!float 1e-8
  total_iter: 100000
  warmup_iter: -1

  # losses
  pixel_opt:
    type: MSELoss
    loss_weight: 1.0
    reduction: mean

#  cx_opt:
#    type: ContextualLoss
#    loss_weight: 1.0
#    band_width: 0.5
#    loss_type: l1
#    use_vgg: true
#    vgg_layer: relu3_4


val:
 val_freq: !!float 2e3
 save_img: true
 metrics:
   psnr: # metric name
     type: calculate_psnr
     crop_border: 0
     test_y_channel: false
   ssim:
     type: calculate_ssim
     crop_border: 0
     test_y_channel: false
#   snr:
#     type: calculate_snr
#   tv:
#     type: calculate_tv

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
#dist_params:
#  backend: nccl
#  port: 29500

