name: SAFMN_FFT_STEM(from sim offline)_p224b8
model_type: SRModel
scale: 1
num_gpu: 1
manual_seed: 12345
color: gray
gt_size: 224
queue_size: 128

datasets:
  train:
    name: ReSe2_Sim_Paired
    type: PairedImageDataset
    color: gray
    dataroot_gt: F:\Datasets\Sim ReSe2\\all_crops_GT
    dataroot_lq: F:\\Datasets\\Sim ReSe2\\all_crops_LQ
    meta_info: ~

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 224
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 10
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: ReSe2_Sim_Paired
    type: PairedImageDataset
    color: gray
    dataroot_gt: F:\Datasets\Sim ReSe2\\all_crops_GT
    dataroot_lq: F:\\Datasets\\Sim ReSe2\\all_crops_LQ
    io_backend:
      type: disk

network_g:
  type: SAFMN_FFT
  in_chans: 1
  dim: 36
  n_blocks: 12
  ffn_scale: 2.0
  upscaling_factor: 1

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0.
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [200000]
    restart_weights: [1]
    eta_min: !!float 1e-6
  total_iter: 200000
  warmup_iter: -1

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  fft_opt:
    type: FFTLoss
    loss_weight: 0.05
    reduction: mean

val:
 val_freq: !!float 2e4
 save_img: true
 metrics:
   psnr: # metric name
     type: calculate_psnr
     crop_border: 0
     test_y_channel: false
   ssim:
     type: calculate_ssim
     crop_border: 0
     test_y_channel: false
   niqe:
     type: calculate_niqe
     crop_border: 0
     test_y_channel: false
     better: lower

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

