name: InstructIR_32_2248_12_2222_p256b8_2gpu
model_type: InstructIRModel
scale: 1
num_gpu: 1
manual_seed: 12345

gt_size: 256

datasets:
  train:
    name: TEMImageNet3k
    type: InstructIRDataset
    phase: train
    color: gray
    dataset_root: /mnt/f/datasets/InstructSTEMIR
    meta_info: /mnt/f/datasets/InstructSTEMIR/meta_info_train.csv
    instruct_meta_info: /mnt/f/Datasets/InstructSTEMIR/instructs.csv
    lm_path: ./models/bge-micro-v2
    lm_head_weight_path: ./models/lm_head/model_head_512_epoch40.pth
    io_backend:
      type: disk
    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 20
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: TEMImageNet3k
    type: InstructIRDataset
    phase: val
    color: gray
    dataset_root: /mnt/f/datasets/InstructSTEMIR
    meta_info: /mnt/f/datasets/InstructSTEMIR/meta_info_val.csv
    lm_head_weight_path: ./models/lm_head/model_head_512_epoch40.pth
    lm_path: ./models/bge-micro-v2
    io_backend:
      type: disk

network_g:
  type: InstructIR
  img_channel: 1
  width: 32
  enc_blk_nums: [2,2,4,8]
  middle_blk_num: 12
  dec_blk_nums: [2,2,2,2]
  txtdim: 512

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0.
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    gamma: 0.5
    milestones: [50000]
  total_iter: 50000
  warmup_iter: -1

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  fft_opt:
    type: FFTLoss
    loss_weight: 0.1
    reduction: mean

val:
 val_freq: !!float 2e3
 save_img: true
 metrics:
   psnr: # metric name
     type: calculate_psnr
     crop_border: 0
     test_y_channel: false
   ssim:
     type: calculate_ssim
     crop_border: 0
     test_y_channel: false


# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500


