# general settings
name: 110_ZSSRInternalx2_TEMImageNet(bic128)_bat128_inc3feature64crop64_lr1e-4_20000iters
model_type: InternalModel
scale: 2
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10
crop_size: 64
use_degradation: false
# dataset and data loader settings
datasets:
  train:
    name: TEMImageNet
    type: InternalDataset
    dataroot_lq: D:/Datasets/TEM-ImageNet-v1.3-master/noBackgroundnoNoise_bic128
    filename_tmpl: '{}'
    io_backend:
      type: disk
    use_degradation: false
    gt_size: 256
    use_hflip: false
    use_rot: false

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
  val:
    name: TEMImageNet_clean
    type: PairedImageDataset
    dataroot_gt: D:/Datasets/TEM-ImageNet-v1.3-master/noBackgroundnoNoise/full
    dataroot_lq: D:/Datasets/TEM-ImageNet-v1.3-master/noBackgroundnoNoise_bic128/
    io_backend:
      type: disk
  val_2 :
    name: TEMImageNet
    type: PairedImageDataset
    dataroot_gt: D:/Datasets/TEM-ImageNet-v1.3-master/noBackgroundnoNoise/full
    dataroot_lq: D:/Datasets/TEM-ImageNet-v1.3-master/image_bic128/
    io_backend:
      type: disk

# network structures
network_g:
  type: ZSSRNet
  input_channels: 3
  kernel_size: 3
  channels: 64
  sr_factor: 2

# path
path:
  pretrain_network_g: ~
  strict_load_g: False
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [10000, 15000]
    gamma: 0.5

  total_iter: 20000
  warmup_iter: 0

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean


# validation settings
val:
  val_freq: !!float 20000
  save_img: false

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
      better: higher
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
      better: higher
    niqe:
      type: calculate_niqe
      crop_border: 0
      test_y_channel: false
      better: lower

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 4000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
#dist_params:
#  backend: nccl
#  port: 29500
