name: DegAE_InstructIR_TEM_t256_p128b4_scratch
model_type: DegAE_InstructIRModel
scale: 1
num_gpu: 1
manual_seed: 12345

gt_size: 128

datasets:
  train:
    name: InstSIP
    type: InstructIRDataset
    phase: train
    color: gray
    dataset_root: /root/autodl-tmp
    meta_info: /root/autodl-tmp/meta_info_train.csv
    instruct_meta_info: /root/autodl-tmp/inst_all.csv
    lm_path: /root/TEMSR/models/bge-micro-v2
    lm_head_weight_path: /root/TEMSR/models/lm_head/model_head_256_dn_db_dd_ll_epoch90.pth
    text_dim: 256
    task_num: 4
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 50
    prefetch_mode: cuda
    pin_memory: true

  val_1:
    name: InstSIP_Denoise
    type: InstructIRDataset
    phase: val
    color: gray
    dataset_root: /root/autodl-tmp
    meta_info: /root/autodl-tmp/meta_info_val_denoise.csv
    lm_path: /root/TEMSR/models/bge-micro-v2
    lm_head_weight_path: /root/TEMSR/models/lm_head/model_head_256_dn_db_dd_ll_epoch90.pth
    text_dim: 256
    task_num: 4
    io_backend:
      type: disk

  val_2:
    name: InstSIP_DeBG
    type: InstructIRDataset
    phase: val
    color: gray
    dataset_root: /root/autodl-tmp
    meta_info: /root/autodl-tmp/meta_info_val_debg.csv
    lm_path: /root/TEMSR/models/bge-micro-v2
    lm_head_weight_path: /root/TEMSR/models/lm_head/model_head_256_dn_db_dd_ll_epoch90.pth
    text_dim: 256
    task_num: 4
    io_backend:
      type: disk

  val_3:
    name: InstSIP_DeDistortion
    type: InstructIRDataset
    phase: val
    color: gray
    dataset_root: /root/autodl-tmp
    meta_info: /root/autodl-tmp/meta_info_val_dedistortion.csv
    lm_path: /root/TEMSR/models/bge-micro-v2
    lm_head_weight_path: /root/TEMSR/models/lm_head/model_head_256_dn_db_dd_ll_epoch90.pth
    text_dim: 256
    task_num: 4
    io_backend:
      type: disk

  val_4:
    name: InstSIP_LLIE
    type: InstructIRDataset
    phase: val
    color: gray
    dataset_root: /root/autodl-tmp
    meta_info: /root/autodl-tmp/meta_info_val_llie.csv
    lm_path: /root/TEMSR/models/bge-micro-v2
    lm_head_weight_path: /root/TEMSR/models/lm_head/model_head_256_dn_db_dd_ll_epoch90.pth
    text_dim: 256
    task_num: 4
    io_backend:
      type: disk

network_g:
  type: DegAE_InstructIR
  inp_channels: 1
  head_channels: 64
  dim: 48
  num_blocks: [ 4,6,6,8 ]
  num_refinement_blocks: 4
  heads: [ 1,2,4,8 ]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  dual_pixel_task: false
  global_residual: false
  text_dim: 256
  decoder_blk_nums: [2,2,2,2]

# path
path:
  pretrain_network_g: ~
  pretrain_network_encoder: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  freeze_encoder: false
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: 0.
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    gamma: 0.5
    milestones: [150000, 300000]
  total_iter: 500000
  warmup_iter: -1

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  fft_opt:
    type: FFTLoss
    loss_weight: 0.1
    reduction: mean

val:
 val_freq: !!float 2e4
 save_img: true
 metrics:
   psnr: # metric name
     type: calculate_psnr
     crop_border: 0
     test_y_channel: false
   ssim:
     type: calculate_ssim
     crop_border: 0
     test_y_channel: false


# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
