name: DegAE_InstructIR_TEM_t256_freeze
model_type: DegAE_InstructIRModel
scale: 1
num_gpu: 1
manual_seed: 12345

gt_size: 128


datasets:
  train:
    name: InstSIP
    type: InstructIRDataset
    phase: train
    color: gray
    dataset_root: D:/Datasets/DegAEFT
    meta_info: D:/Datasets/DegAEFT/meta_info_train.csv
    instruct_meta_info: D:/Datasets/DegAEFT/inst_all.csv
    lm_path: F:/github/TEMSR/models/bge-micro-v2
    lm_head_weight_path: F:/github/TEMSR/models/lm_head/model_head_256_dn_db_dd_ll_epoch90.pth
    text_dim: 256
    task_num: 4
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 1
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 10
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: InstSIP
    type: InstructIRDataset
    phase: val
    color: gray
    dataset_root: D:/Datasets/DegAEFT
    meta_info: D:/Datasets/DegAEFT/meta_info_val_small.csv
    lm_path: F:/github/TEMSR/models/bge-micro-v2
    lm_head_weight_path: F:/github/TEMSR/models/lm_head/model_head_256_dn_db_dd_ll_epoch90.pth
    text_dim: 256
    task_num: 4
    io_backend:
      type: disk

network_g:
  type: DegAE_InstructIR
  inp_channels: 1
  out_channels: 64
  dim: 48
  num_blocks: [ 4,6,6,8 ]
  num_refinement_blocks: 4
  heads: [ 1,2,4,8 ]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  dual_pixel_task: False
  global_residual: False
  text_dim: 256
  decoder_blk_nums: [2,2,2,2]

# path
path:
  pretrain_network_encoder: F:/Project/DegAE_DegradationAutoencoder-main/Pretrain_DegAE_Restormer/80000_PretrainEncoder.pth
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  freeze_encoder: true
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0.
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    gamma: 0.5
    milestones: [100000, 200000]
  total_iter: 300000
  warmup_iter: -1

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  fft_opt:
    type: FFTLoss
    loss_weight: 0.05
    reduction: mean

val:
 val_freq: !!float 5e3
 save_img: true
 metrics:
   psnr: # metric name
     type: calculate_psnr
     crop_border: 0
     test_y_channel: false
   ssim:
     type: calculate_ssim
     crop_border: 0
     test_y_channel: false


# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500


