# general settings
name: 104_RCANInternalx2(hld)_pretrained_TEMSR(deg)_bat32_lr1e-4_2000iters
model_type: InternalModel
scale: 2
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10
crop_size: 64
gt_size: 256

# high-level degradtion
gaussian_noise_prob: 0.5
noise_range: [1, 30]
poisson_scale_range: [0.05, 3]
gray_noise_prob: 0.4
jpeg_range: [10, 20]

second_blur_prob: 0.8
gaussian_noise_prob2: 0.5
noise_range2: [1, 25]
poisson_scale_range2: [0.05, 2.5]
gray_noise_prob2: 0.4
jpeg_range2: [10, 20]

# dataset and data loader settings
datasets:
  train:
    name: TEMSR_Deg
    type: InternalDataset
    dataroot_lq: D:/Datasets/TEMPatch for SR/LQ/Train
    # D:/Datasets/TEMPatch for SR/2/orig
    # meta_info: D:/github/TEMSR_BasicSR/basicsr/data/meta_info/meta_info_TEMImageNet_GT.txt
    io_backend:
      type: disk

    use_degradation: true
    blur_kernel_size: 9
    kernel_list: [ 'iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso' ]
    kernel_prob: [ 0.45, 0.25, 0.12, 0.03, 0.12, 0.03 ]
    sinc_prob: 0.1
    blur_sigma: [ 0.2, 3 ]
    betag_range: [ 0.5, 4 ]
    betap_range: [ 1, 2 ]

    blur_kernel_size2: 9
    kernel_list2: [ 'iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso' ]
    kernel_prob2: [ 0.45, 0.25, 0.12, 0.03, 0.12, 0.03 ]
    sinc_prob2: 0.1
    blur_sigma2: [ 0.2, 1.5 ]
    betag_range2: [ 0.5, 4 ]
    betap_range2: [ 1, 2 ]

    final_sinc_prob: 0.8

    gt_size: 256
    use_hflip: false
    use_rot: false

    # data loader
    num_worker_per_gpu: 1
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: TEMSR_deg_val
    type: PairedImageDataset
    dataroot_gt: D:/Datasets/TEMPatch for SR/GT/Train
    dataroot_lq: D:/Datasets/TEMPatch for SR/LQ/Train
    io_backend:
      type: disk

# network structures
network_g:
  type: RCAN_Internal
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_group: 6
  num_block: 10
  squeeze_factor: 16
  upscale: 2
  res_scale: 1
  img_range: 255.
  rgb_mean: [0.1980, 0.1980, 0.1980]

# path
path:
  pretrain_network_g: D:/github/TEMSR_BasicSR/experiments/pretrained_models/RCAN/101_RCANx2_scratch_TEMImageNet_bat8_inc3feature64group6block10_lr1e-4_240000.pth
  strict_load_g: False
  resume_state: ~

# training settings
train:
  ema_decay: 0
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100, 500, 1000]
    gamma: 0.8

  total_iter: 2000
  warmup_iter: 0

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
#  perceptual_opt:
#    type: PerceptualLoss
#    layer_weights:
#      # before relu
#      'conv1_2': 0.1
#      'conv2_2': 0.1
#      'conv3_4': 1
#      'conv4_4': 1
#      'conv5_4': 1
#    vgg_type: vgg19
#    use_input_norm: true
#    perceptual_weight: !!float 1.0
#    style_weight: 0
#    range_norm: false
#    criterion: l1

# validation settings
val:
  val_freq: !!float 200
  save_img: false

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
      better: higher
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
      better: higher
#    niqe:
#      type: calculate_niqe
#      crop_border: 0
#      test_y_channel: false
#      better: lower

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 200
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
#dist_params:
#  backend: nccl
#  port: 29500
