name: NAFNet-2222_12_2248_p256b8_SR fft0.02 enlarge10
model_type: SRModel
scale: 1
num_gpu: 1
manual_seed: 12345

gt_size: 256


datasets:
  train:
    name: InstSIP_SR
    type: PairedImageDataset
    color: gray
    dataroot_gt: /mnt/d/Datasets/InstSIP/Super-Resolution/train/HQ
    dataroot_lq: /mnt/d/Datasets/InstSIP/Super-Resolution/train/LQ
    meta_info: ~

    filename_tmpl: '{}'
    io_backend:
      type: disk
    gt_size: 256
    use_hflip: true
    use_rot: true
    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 10
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: InstSIP_SR
    type: PairedImageDataset
    color: gray
    dataroot_gt: /mnt/d/Datasets/InstSIP/Super-Resolution/val/HQ
    dataroot_lq: /mnt/d/Datasets/InstSIP/Super-Resolution/val/LQ
    io_backend:
      type: disk


network_g:
  type: NAFNet
  width: 32
  enc_blk_nums: [2, 2, 4, 8]
  middle_blk_num: 12
  dec_blk_nums: [ 2, 2, 2, 2 ]
  img_channel: 1

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0.
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000]
    gamma: 0.5
  total_iter: 50000
  warmup_iter: -1

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  fft_opt:
    type: FFTLoss
    loss_weight: 0.02
    reduction: mean

val:
 val_freq: !!float 2e3
 save_img: true
 metrics:
   psnr: # metric name
     type: calculate_psnr
     crop_border: 0
     test_y_channel: false
   ssim:
     type: calculate_ssim
     crop_border: 0
     test_y_channel: false

# logging settings
logger:
  print_freq: 10000
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

