name: SwinMAEIR_STEM_p56b32
model_type: SRModel
pretrain_mae_ckpt: /mnt/f/mae-main/output_dir/checkpoint-40.pth
scale: 1
num_gpu: 1
manual_seed: 12345
gt_size: 56
queue_size: 180

datasets:
  train:
    name: TEMImageNet_Denoising
    type: PairedImageDataset
    color: gray
    dataroot_gt: /mnt/f/Datasets/TEM-ImageNet-v1.3-master/noBackgroundnoNoise/train
    dataroot_lq: /mnt/f/Datasets/TEM-ImageNet-v1.3-master/image/train
    meta_info: ~

    filename_tmpl: '{}'
    io_backend:
      type: disk
    gt_size: 56
    use_hflip: true
    use_rot: true
    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 5
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: TEMImageNet_Denoising
    type: PairedImageDataset
    use_pbar: true
    color: gray
    dataroot_gt: /mnt/f/Datasets/TEM-ImageNet-v1.3-master/noBackgroundnoNoise/val224
    dataroot_lq: /mnt/f/Datasets/TEM-ImageNet-v1.3-master/image/val224
    io_backend:
      type: disk


network_g:
  type: SwinMAEIR
  window_masking_r: 4
  upscale: 1
  img_size: 56
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: denoising
  in_chans: 1

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: 0.
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000]
    gamma: 1
  total_iter: 50000
  warmup_iter: -1

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  fft_opt:
    type: FFTLoss
    loss_weight: 0.01
    reduction: mean

val:
 val_freq: !!float 2e3
 save_img: true
 metrics:
   psnr: # metric name
     type: calculate_psnr
     crop_border: 0
     test_y_channel: false
   ssim:
     type: calculate_ssim
     crop_border: 0
     test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

