name: SwinUNet_ft_p256w16b8_TEMImageNet500denoise fft0.02 enlarge10 norm nofreeze
model_type: SwinUNetModel
scale: 1
num_gpu: 1
manual_seed: 12345
gt_size: 256
mean: 0.1682
std: 0.1582

datasets:
  train:
    name: TEMImageNet_Denoise_500
    type: PairedImageDataset
    color: gray
    dataroot_gt: /mnt/f/Datasets/InstructSTEMIR/Denoise/GT/TEMImageNet500
    dataroot_lq: /mnt/f/Datasets/InstructSTEMIR/Denoise/LQ/TEMImageNet500
    meta_info: ~
    mean: 0.1682
    std: 0.1582

    io_backend:
      type: disk
    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 10
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: TEMImageNet_Denoise_val500
    type: PairedImageDataset
    color: gray
    dataroot_gt: /mnt/f/Datasets/InstructSTEMIR/Denoise/GT/TEMImageNet_val500
    dataroot_lq: /mnt/f/Datasets/InstructSTEMIR/Denoise/LQ/TEMImageNet_val500
    io_backend:
      type: disk
    mean: 0.1682
    std: 0.1582


network_g:
  type: Swinv2UNet
  img_size: 256
  patch_size: 4
  in_chans: 1
  num_classes: 1
  embed_dim: 128
  depths: [2, 2, 18, 2]
  depths_decoder: [2, 2, 2, 2]
  num_heads: [4, 8, 16, 32]
  window_size: 16
  mlp_ratio: 4
  qkv_bias: True
  drop_rate: 0
  drop_path_rate: 0.1
  ape: False
  patch_norm: True
  freeze_encoder: False


# path
path:
  pretrain_network_g_e: ~
  param_key_g_e: model
  pretrain_network_g: ~
  param_key_g: params
  strict_load_g: False
  resume_state: ./experiments/SwinUNet_ft_p256w16b8_TEMImageNet500denoise fft0.02 enlarge10 norm nofreeze/training_states/8000.state

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0.
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    gamma: 0.5
    milestones: [10000]
  total_iter: 30000
  warmup_iter: -1

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  fft_opt:
    type: FFTLoss
    loss_weight: 0.02
    reduction: mean

val:
 val_freq: !!float 1e3
 save_img: true
 metrics:
   psnr: # metric name
     type: calculate_psnr
     crop_border: 0
     test_y_channel: false
   ssim:
     type: calculate_ssim
     crop_border: 0
     test_y_channel: false


# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

