name: SwinUNet_ft_p256w16b8_Exp2kdenoise fft0.1 norm nofreeze
model_type: SwinUNetModel
scale: 1
num_gpu: 1
manual_seed: 12345
gt_size: 256
mean: 0.2944
std: 0.1450

datasets:
  train:
    name: ExpimageDenoise_train2k
    type: PairedImageDataset
    color: gray
    dataroot_gt: /mnt/d/Datasets/PairsEXP/HQ256/train
    dataroot_lq: /mnt/d/Datasets/PairsEXP/LQ256/train
    meta_info: ~
    mean: 0.2944
    std: 0.1450

    io_backend:
      type: disk
    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 10
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: ExpimageDenoise_val300
    type: PairedImageDataset
    color: gray
    dataroot_gt: /mnt/d/Datasets/PairsEXP/HQ256/val
    dataroot_lq: /mnt/d/Datasets/PairsEXP/LQ256/val
    io_backend:
      type: disk
    mean: 0.2944
    std: 0.1450


network_g:
  type: Swinv2UNet
  img_size: 256
  patch_size: 4
  in_chans: 1
  out_chans: 1
  embed_dim: 128
  depths: [2, 2, 18, 2]
  depths_decoder: [2, 2, 2, 2]
  num_heads: [4, 8, 16, 32]
  window_size: 16
  mlp_ratio: 4
  qkv_bias: True
  drop_rate: 0
  drop_path_rate: 0.1
  ape: False
  patch_norm: True
  freeze_encoder: False


# path
path:
  pretrain_network_g_e: ./models/swinv2/ckpt_epoch_70.pth
  param_key_g_e: model
  pretrain_network_g: ~
  param_key_g: params
  strict_load_g: False
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0.
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    gamma: 0.5
    milestones: [15000]
  total_iter: 30000
  warmup_iter: -1

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  fft_opt:
    type: FFTLoss
    loss_weight: 0.1
    reduction: mean
#  tv_opt:
#    type: TVLoss
#    loss_weight: 1

val:
 val_freq: !!float 1e3
 save_img: true
 metrics:
   psnr: # metric name
     type: calculate_psnr
     crop_border: 0
     test_y_channel: false
   ssim:
     type: calculate_ssim
     crop_border: 0
     test_y_channel: false


# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

