name: MAEIR_STEM_dim512NAF1111_p224_b32
model_type: SRModel
scale: 1
num_gpu: 1
manual_seed: 12345
gt_size: 224
queue_size: 180

datasets:
  train:
    name: TEMImageNet_Denoising
    type: PairedImageDataset
    color: gray
    dataroot_gt: /mnt/f/Datasets/TEM-ImageNet-v1.3-master/noBackgroundnoNoise/train
    dataroot_lq: /mnt/f/Datasets/TEM-ImageNet-v1.3-master/image/train
    meta_info: ~

    filename_tmpl: '{}'
    io_backend:
      type: disk
    gt_size: 224
    use_hflip: true
    use_rot: true
    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 5
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: TEMImageNet_Denoising
    type: PairedImageDataset
    color: gray
    dataroot_gt: /mnt/f/Datasets/TEM-ImageNet-v1.3-master/noBackgroundnoNoise/val224
    dataroot_lq: /mnt/f/Datasets/TEM-ImageNet-v1.3-master/image/val224
    io_backend:
      type: disk


network_g:
  type: MAEIR
  img_size: 224
  patch_size: 16
  in_chans: 1
  embed_dim: 1024
  depth: 24
  num_heads: 16
  decoder_embed_dim: 512
  decoder_blks: [1, 1, 1, 1]
  mlp_ratio: 4

# path
path:
  pretrain_network_g: /mnt/f/Project/mae-main/output_dir/mae_large/checkpoint-80.pth
  param_key_g: model
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: 0.
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000]
    gamma: 1
  total_iter: 50000
  warmup_iter: -1

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  fft_opt:
    type: FFTLoss
    loss_weight: 0.01
    reduction: mean

val:
 val_freq: !!float 2e3
 save_img: true
 metrics:
   psnr: # metric name
     type: calculate_psnr
     crop_border: 0
     test_y_channel: false
   ssim:
     type: calculate_ssim
     crop_border: 0
     test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

